### ISSUE TITLE
Connecting to a redis schema url

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [mediocregopher/radix.v3#36]
I'm trying to connect to a redis schema URL, but I keep getting error. Is there any documentation or help on this?

Sample url:
`redis://h:asdfqwer1234asdf@ec2-111-1-1-1.compute-1.amazonaws.com:38799`

And this is the code I use to connect:

```golang
        fmt.Println("running")
	client, err := radix.NewPool("tcp", "redis://h:asdfqwer1234asdf@ec2-111-1-1-1.compute-1.amazonaws.com:38799", 10)
	if err != nil {
		// handle error
	}

	var fooVal string
	err = client.Do(radix.Cmd(&fooVal, "SET", "foo", "hello"))
	fmt.Println(err, fooVal)
```

I've also tried to do `[redis://h:asdfqwer1234asdf@ec2-111-1-1-1.compute-1.amazonaws.com]:38799` and use it.

This is the error:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f2b7e]

goroutine 1 [running]:
github.com/mediocregopher/radix%2ev3.(*Pool).getExisting(0x0, 0x0, 0x0, 0x0)
	/home/aks/go/src/github.com/mediocregopher/radix.v3/pool.go:365 +0x4e
github.com/mediocregopher/radix%2ev3.(*Pool).get(0x0, 0x40aa78, 0x51afe0, 0x525120)
	/home/aks/go/src/github.com/mediocregopher/radix.v3/pool.go:403 +0x2f
github.com/mediocregopher/radix%2ev3.(*Pool).Do(0x0, 0x7f88d84f70c0, 0xc0000c2000, 0x0, 0x0)
	/home/aks/go/src/github.com/mediocregopher/radix.v3/pool.go:440 +0x37
main.main()
	/home/aks/hello.go:17 +0x19e
exit status 2
```

**Comment by mediocregopher** [comment]
I went ahead and made Dial accept URIs like yours, so your original example should work properly now. Thanks!
